### DISCUSSION TITLE
h2 database 관련

### DISCUSSION THREAD

**Discussion by supra1nova** [supra1nova/fc-project-board#15] [General]
```
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    driver-class-name: org.h2.Driver
  h2.console.enabled: true
```

https://www.h2database.com/html/main.html
